  <div class="pp-buttons-container" id="showListIp" data-bind="scope: 'showListIp'">         
    <button id="<?php echo $block->getHtmlId() ?>"  data-action="choose"
                        data-bind="click: open">
        <span><span><span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span></span></span>
    </button>
</div>

        <!-- Select Associated Product popup -->
        <div id="ips-list">
            <div class="admin__data-grid-outer-wrap" data-bind="scope: 'OnclickShowListIp'">
                <!-- ko template: getTemplate() --><!-- /ko -->

            </div>
        </div>

<script type="text/x-magento-init">
    {
        "#ips-list": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "showListIp": {
                        "component": "Firebear_CloudFlare/js/iplist",
                        "statisticUrl": "<?=  $block->getUrl($block->getInternUrl()).'?'.$block->getScopeType().'='.$block->getScopeCode() ?>"
                    }
                }
            }
        }
    }
</script>
